"""
report_gen.py
-------------
Assembles a structured Markdown literature review report from
paper summaries, clusters, and identified research gaps.
Responsibilities:
  - Combine all pipeline outputs into a cohesive report
  - Save the report to the outputs/ directory with a timestamp
  - Return the report as a string for display in the Gradio UI
"""

import os
import logging
from datetime import datetime

# ── Logging ────────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("report_gen")

# ── Configuration ──────────────────────────────────────────────────────────────
OUTPUTS_DIR = "outputs"


# ── Report Generator ───────────────────────────────────────────────────────────

def generate_report(
    query:    str,
    papers:   list[dict],
    clusters: list[dict],
    gaps:     list[dict],
) -> str:
    """
    Generate a structured Markdown literature review report.

    Args:
        query:    The original user search query.
        papers:   List of paper dicts with 'summary' key from summarizer.
        clusters: List of cluster dicts from clusterer.
        gaps:     List of gap dicts from gap_analyzer.

    Returns:
        Full Markdown report as a string. Also saved to outputs/ directory.
    """
    os.makedirs(OUTPUTS_DIR, exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M")
    total     = len(papers)
    success   = sum(1 for p in papers if not p.get("summary", {}).get("_failed"))

    lines = []

    # ── Header ─────────────────────────────────────────────────────────────────
    lines += [
        f"# Literature Review: {query}",
        "",
        f"> Generated by Autonomous Research Assistant (ARA) on {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
        "---",
        "",
    ]

    # ── Overview ───────────────────────────────────────────────────────────────
    lines += [
        "## Overview",
        "",
        f"- **Query:** {query}",
        f"- **Papers analyzed:** {success} of {total}",
        f"- **Themes identified:** {len(clusters)}",
        f"- **Research gaps found:** {len(gaps.get('gaps', []) if isinstance(gaps, dict) else gaps)}",
        "",
        "---",
        "",
    ]

    # ── Paper Summaries ─────────────────────────────────────────────────────────
    lines += [
        "## Paper Summaries",
        "",
    ]

    for i, paper in enumerate(papers, 1):
        s = paper.get("summary", {})
        if s.get("_failed"):
            lines += [
                f"### {i}. {paper.get('title', 'Unknown')}",
                "",
                "> Summarization failed for this paper.",
                "",
            ]
            continue

        keywords = ", ".join(s.get("keywords", [])) or "N/A"
        lines += [
            f"### {i}. {s.get('title', 'Unknown')}",
            "",
            f"**Authors:** {s.get('authors', 'N/A')}  ",
            f"**Year:** {s.get('year', 'N/A')}  ",
            f"**Keywords:** {keywords}",
            "",
            f"**Problem:** {s.get('problem', 'N/A')}",
            "",
            f"**Method:** {s.get('method', 'N/A')}",
            "",
            f"**Results:** {s.get('results', 'N/A')}",
            "",
            f"**Limitations:** {s.get('limitations', 'N/A')}",
            "",
        ]

    lines += ["---", ""]

    # ── Thematic Clusters ───────────────────────────────────────────────────────
    lines += [
        "## Thematic Clusters",
        "",
        "Papers grouped by topic similarity:",
        "",
    ]

    # clusters is a dict: {label: [paper_dicts]}
    for i, (theme, cluster_papers) in enumerate(clusters.items(), 1):
        lines += [
            f"### Theme {i}: {theme}",
            "",
        ]
        for cp in cluster_papers:
            title = cp.get("summary", {}).get("title") or cp.get("title", "Unknown")
            year  = cp.get("summary", {}).get("year", "N/A")
            lines.append(f"- {title} ({year})")
        lines.append("")

    lines += ["---", ""]

    # ── Research Gaps ───────────────────────────────────────────────────────────
    lines += [
        "## Identified Research Gaps",
        "",
        "The following open research questions were identified across the literature:",
        "",
    ]

    gap_list = gaps.get("gaps", []) if isinstance(gaps, dict) else gaps
    if not gap_list:
        lines += ["> No research gaps could be identified.", ""]
    else:
        for i, gap in enumerate(gap_list, 1):
            # Handle both dict and string formats from gap_analyzer
            if isinstance(gap, dict):
                title       = gap.get("title", f"Gap {i}")
                description = gap.get("description", "N/A")
                related     = gap.get("relevant_papers", [])
            else:
                title       = f"Gap {i}"
                description = str(gap)
                related     = []

            lines += [
                f"### Gap {i}: {title}",
                "",
                description,
                "",
            ]
            if related:
                lines.append("**Related papers:**")
                for r in related:
                    lines.append(f"- {r}")
                lines.append("")

    lines += ["---", ""]

    # ── References ─────────────────────────────────────────────────────────────
    lines += [
        "## References",
        "",
    ]

    for i, paper in enumerate(papers, 1):
        s       = paper.get("summary", {})
        title   = s.get("title") or paper.get("title", "Unknown")
        authors = s.get("authors") or paper.get("authors", "N/A")
        year    = s.get("year") or paper.get("published", "N/A")[:4]
        url     = paper.get("arxiv_url", "N/A")
        lines.append(f"{i}. {authors} ({year}). *{title}*. {url}")

    lines += ["", "---", ""]
    lines.append(f"*Report generated by ARA — Autonomous Research Assistant*")

    # ── Assemble and Save ───────────────────────────────────────────────────────
    report = "\n".join(lines)

    # Save to outputs/
    safe_query  = "_".join(query.lower().split())[:50]
    output_path = os.path.join(OUTPUTS_DIR, f"report_{safe_query}_{timestamp}.md")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(report)

    logger.info(f"Report saved to: {output_path}")
    return report


# ── Quick test harness ─────────────────────────────────────────────────────────

if __name__ == "__main__":
    from tools.arxiv_search  import search_papers
    from tools.pdf_fetcher   import fetch_papers_text
    from agent.summarizer    import summarize_papers
    from agent.clusterer     import cluster_papers
    from agent.gap_analyzer  import analyze_gaps

    QUERY = "transformer pruning efficient inference"

    print("=" * 60)
    print("ARA — Report Generator Test Harness")
    print("=" * 60)

    # Full pipeline
    print("\nStep 1: Searching arXiv...")
    papers = search_papers(QUERY, max_results=6)

    print("\nStep 2: Fetching PDFs...")
    papers = fetch_papers_text(papers)

    print("\nStep 3: Summarizing papers...")
    papers = summarize_papers(papers)

    print("\nStep 4: Clustering...")
    clusters = cluster_papers(papers)

    print("\nStep 5: Analyzing gaps...")
    gaps = analyze_gaps(papers)

    print("\nStep 6: Generating report...")
    report = generate_report(QUERY, papers, clusters, gaps)

    # Print first 2000 chars as preview
    print("\n" + "=" * 60)
    print("REPORT PREVIEW (first 2000 chars):")
    print("=" * 60)
    print(report[:2000])
    print("\n... (full report saved to outputs/)")